package com.mycompany.proyecto_datos;


import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class Frm_Principal extends javax.swing.JFrame {
    ArrayList<JTextArea> ordenes;
    ArrayList<JButton> botones;

    /**
     * Creates new form Frm_Principal
     */
    public Frm_Principal() {
        Ingredientes in1=new Ingredientes("Pan", 2);
        Ingredientes in2=new Ingredientes("Carne", 3);
        Ingredientes in3=new Ingredientes("Lechuga", 4);
        Ingredientes in4=new Ingredientes("Queso", 5);
        
        Cola c= new Cola();
        /*-------------------------------------*/
        preparacion p1 = new preparacion();
        p1.insert(in1);
        p1.insert(in2);
        p1.insert(in3);
        p1.insert(in4);
        c.insert(p1);
        /*-------------------------------------*/
        preparacion p2= new preparacion();
        p1.insert(in1);
        p1.insert(in2);
        p1.insert(in4);
        c.insert(p2);
        /*-------------------------------------*/
        preparacion p3=new preparacion ();
        p1.insert(in1);
        p1.insert(in2);
        c.insert(p3);
        /*-------------------------------------*/
        ordenes = new ArrayList<>();
        ordenes.add(Pantalla1);
        ordenes.add(Pantalla2);
        ordenes.add(Pantalla3);
        /*-------------------------------------*/
        this.prepa = new preparacion();
        botones = new ArrayList<>();
        /*-------------------------------------*/
        botones.add(btn_pan);
        botones.add(btn_carne);
        botones.add(btn_queso);
        botones.add(btn_lechuga);
        /*-------------------------------------*/
        
        /*-----------------ACTUALIZACIONES--------------------*/
        update();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_pan = new javax.swing.JButton();
        btn_carne = new javax.swing.JButton();
        btn_queso = new javax.swing.JButton();
        btn_lechuga = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Pantalla1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Pantalla2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Pantalla3 = new javax.swing.JTextArea();
        btn_servirorden = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        tiempo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn_menu = new javax.swing.JMenu();
        mn_cerrar_sesion = new javax.swing.JMenuItem();
        mn_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(94, 94, 94));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/surgery_icon_150141.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_pan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pann.jpeg"))); // NOI18N
        btn_pan.setText("Pan");
        btn_pan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_panActionPerformed(evt);
            }
        });

        btn_carne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carni.jpeg"))); // NOI18N
        btn_carne.setText("Carne");
        btn_carne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carneActionPerformed(evt);
            }
        });

        btn_queso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/quesi.jpeg"))); // NOI18N
        btn_queso.setText("Queso");
        btn_queso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quesoActionPerformed(evt);
            }
        });

        btn_lechuga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lechugi.jpeg"))); // NOI18N
        btn_lechuga.setText("Lechuga");
        btn_lechuga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lechugaActionPerformed(evt);
            }
        });

        Pantalla1.setColumns(20);
        Pantalla1.setLineWrap(true);
        Pantalla1.setRows(5);
        Pantalla1.setText("1.");
        jScrollPane4.setViewportView(Pantalla1);

        Pantalla2.setColumns(20);
        Pantalla2.setLineWrap(true);
        Pantalla2.setRows(5);
        Pantalla2.setText("2.");
        jScrollPane3.setViewportView(Pantalla2);

        Pantalla3.setColumns(20);
        Pantalla3.setLineWrap(true);
        Pantalla3.setRows(5);
        Pantalla3.setText("3.");
        jScrollPane2.setViewportView(Pantalla3);

        btn_servirorden.setText("Servir Orden");
        btn_servirorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_servirordenActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(jTextPane2);

        jTextArea4.setColumns(20);
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("Puntos: ");
        jScrollPane5.setViewportView(jTextArea4);

        tiempo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        tiempo.setText("Tiempo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_servirorden, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(btn_pan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(btn_carne, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(btn_queso, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(btn_lechuga, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_carne, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_queso, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_lechuga, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_servirorden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        mn_menu.setText("Salir");

        mn_cerrar_sesion.setText("Cerrar Sesión");
        mn_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_cerrar_sesionActionPerformed(evt);
            }
        });
        mn_menu.add(mn_cerrar_sesion);

        mn_salir.setText("Salir del Sistema");
        mn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_salirActionPerformed(evt);
            }
        });
        mn_menu.add(mn_salir);

        jMenuBar1.add(mn_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void iniciar_sistema (){   
        //Creo un objeto de la clase formulario inicio sesión
        Frm_Inicio_Sesion inicio= new Frm_Inicio_Sesion();
                
        //Definimos un título para la cabecera del formulario
        inicio.setTitle("");
        
        //Permite centrar un formulario en pantalla
        inicio.setLocationRelativeTo(null);
        
        //Definir la dimensiones del formulario
        
        //Hacer visible el formulario en pantalla
        inicio.setVisible(true);
                
    }
    private void mn_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_cerrar_sesionActionPerformed
       
        this.dispose();
        
        Frm_Inicio_Sesion inicio = new Frm_Inicio_Sesion();
        
        inicio.setTitle("Ingreso al Sistema de creacion de hamburguesas");
        
        inicio.setLocationRelativeTo(null);
        
        inicio.setVisible(true);
        
    }//GEN-LAST:event_mn_cerrar_sesionActionPerformed

    private void mn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_salirActionPerformed
      
        this.dispose();
        
    }//GEN-LAST:event_mn_salirActionPerformed

    private void btn_panActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_panActionPerformed
        // TODO add your handling code here:
        this.prepa.insert(banda.extract(btn_pan.getText()));
        borrar();

    }//GEN-LAST:event_btn_panActionPerformed

    private void btn_servirordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_servirordenActionPerformed
        // TODO add your handling code here:
                this.dispose();
            
            Frm_Registro_Hamburguesa regis = new Frm_Registro_Hamburguesa();
            
            regis.setTitle("Información de las ordenes realizadas");
           
            regis.setLocationRelativeTo(null);
            
            regis.setVisible(true);
          
    }//GEN-LAST:event_btn_servirordenActionPerformed

    private void btn_carneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carneActionPerformed
        // TODO add your handling code here:
        this.prepa.insert(banda.extract(btn_carne.getText()));
        borrar();
    }//GEN-LAST:event_btn_carneActionPerformed

    private void btn_quesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quesoActionPerformed
        // TODO add your handling code here:
        this.prepa.insert(banda.extract(btn_queso.getText()));
        borrar();
    }//GEN-LAST:event_btn_quesoActionPerformed

    private void btn_lechugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lechugaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lechugaActionPerformed
    public void borrar(){
        update();
    }
    public void update(){
        int contador =0;
        for (JButton button : botones){
            button.setText(this.prepa.InPos(contador));
            contador++;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Principal().setVisible(true);
            }
        });
    }
    private static listaBanda banda;
    private static preparacion prepa;
    int puntosJugador;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Pantalla1;
    private javax.swing.JTextArea Pantalla2;
    private javax.swing.JTextArea Pantalla3;
    private javax.swing.JButton btn_carne;
    private javax.swing.JButton btn_lechuga;
    private javax.swing.JButton btn_pan;
    private javax.swing.JButton btn_queso;
    private javax.swing.JButton btn_servirorden;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JMenuItem mn_cerrar_sesion;
    private javax.swing.JMenu mn_menu;
    private javax.swing.JMenuItem mn_salir;
    private javax.swing.JLabel tiempo;
    // End of variables declaration//GEN-END:variables
}
